blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import PostsFeeds

urlpatterns = [
	url(r'^$', views.post_list_view, name = 'post_list_view'),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail_view, name='post_detail_view'),
	url(r'^feeds/$', PostsFeeds(), name="post_feed")
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
	'posts':PostSitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps':sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class DatePublishedManager(models.Manager):
	def get_queryset(self):
		return super(DatePublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
	STATUS_CHOICES = (
		('draft','Draft'),
		('published','Published'),
	)
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique_for_date='date_published')
	author = models.ForeignKey(User, related_name='blog_posts')
	body = models.TextField()
	date_published = models.DateTimeField(default=timezone.now)
	date_created = models.DateTimeField(auto_now_add=True)
	last_updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10, choices=STATUS_CHOICES)

	#default manager
	objects = models.Manager()

	#custom manager
	published = DatePublishedManager()

	class Meta:
		ordering = ('-date_published',)	

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post_detail_view', args=[self.date_published.year, self.date_published.strftime('%m'), self.date_published.strftime('%d'), self.slug])
		

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post

def post_list_view(request):
	list_objects = Post.published.all()
	paginator = Paginator(list_objects, 2)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	return render(request, 'blog/post/list.html', {'posts':posts})

def post_detail_view(request, year, month, day, post):
	post = get_object_or_404(Post, slug=post, status='published', date_published__year=year, date_published__month = month, date_published__day = day)
	return render(request, 'blog/post/detail.html', {'post':post})

blog/templates/blog/master.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang='en'>

<head>
	<meta charset="UTF-8">
	<title>{% block title  %}{% endblock %} </title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>
	<div class = 'container'>
		<div class = 'row'>
			<div class = 'col-md-8'>
				{% block content%}

				{% endblock %}
			</div>
			<div class = 'col-md-4'>
				<h3 class="page-header">Ricky's Django Blog</h3>
				<p><a href="{% url 'blog:post_feed' %}" target="_blank"></a>Subscibe to RSS Feed</p>
			</div>
			<div id="fb-root"></div>
				<script>
					(function(d, s, id) {
					  var js, fjs = d.getElementsByTagName(s)[0];
					  if (d.getElementById(id)) return;
					  js = d.createElement(s); js.id = id;
					  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12';
					  fjs.parentNode.insertBefore(js, fjs);
					}(document, 'script', 'facebook-jssdk'));
				</script>
		</div>
	</div>
</body>

</html>

blog/templates/blog/post/detail.html
{% extends "blog/master.html" %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
<div class="row">
	<h3>{{ post.title }}</h3>
	<p class = 'small'>Published {{ post.date_published }} by {{ post.author }}</p>
	<p>{{ post.body|linebreaks }}</p>
	<div class="fb-comments" data-href="{{ post.build_absolute_uri }}" data-numposts = "5"></div>
</div>
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/master.html" %}

{% block title %}Django Blog{% endblock %}

{% block content %}
	<h2 class='page-header'>Recent Posts</h2>
	{% for post in posts%}
		<h3><a href = "{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
		<p class="small" style="color: #777777">Published {{ post.date_published }} by {{ post.author }} </p>
		<p>{{ post.body|truncatewords:25|linebreaks }}</p>
	{% endfor %}

	{% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/pagination.html
<div class="container">
	<div class="row">
		<span class="pagination">
			{% if page.has_previous %}
				<a href="?page={{ page.previous_page_number }}">previous</a>
			{% endif %}

			<span class="active">
				page {{ page.number }} of {{ page.paginator.num_pages }}
			</span>

			{% if page.has_next %}
				<a href="?page={{ page.next_page_number }}">next</a>
			{% endif %}
		</span>
	</div>
</div>